
etcd:
  endpoints:
    - http://localhost:2379

  # watch対象のetcdのkeyのリスト
  watch_targets:
    - /watch_target/key01
    - /watch_target/key02

  # 複数台で動かした際に、同じイベントを通知しないようにロック用keyを作るためのディレクトリ
  lock_dir: /lock/

slack:
  incoming_webhook_url: your_webhook_url

  # dry_runモードの場合はpayloadをログに出力するだけ。
  dry_run: false

  # outgoing webhookの設定
  hook:
    # outgoing webhook有効にするかどうか
    enable: true

    # port
    port: 8080

    # POSTされてくるtoken, 設定してない場合はtokenのチェックを行わない
    token: YOUR_TOKEN

    # botを仕込んだチャンネル, 設定してない場合はチャンネルのチェックを行わない
    channel_name: test_channel

    # botの名前
    torigger_word: "etcdbot:"
